"use strict"

// Declare our module
var myApp = angular.module( 'contactListApp', ['ngRoute'] );

// Add our controller to our module
myApp.controller( 'contactListCtrl', function( $scope, $http, $location )
{
	// A variable to use to generate ids (primary key) for each contact that 
	// is generated by this app.  The contacts from the server should have id already
	$scope.contact_id_generator = false;

	// The templates available to our app
	$scope.templates = [ 
		{ name: 'list', url: 'templates/contacts_list.html' }
		,{ name: 'table', url: 'templates/contacts_table.html' } ];

	if( $scope.template === undefined )
		$scope.template = $scope.templates[0];

	// Make sure we only load the contact information once
	$scope.bContactsLoaded = false;

	if( $scope.contacts === undefined )
	{
		// Load the contact list from the server
		$http.get( 'data/contacts.php' ).success( function( data )
		{
			$scope.contacts = data;

			// Set the id generator to the id of the last contact loaded from the server
			// plus one (so we don't need a backend and so the code will be easily used with a backend)
			$scope.contact_id_generator = $scope.contacts.length;
		} );
	}

	// Load the list of states from the server
	$http.get( 'data/states.php' ).success( function( data )
	{
		$scope.states = data;
	} );

	// The text used to filter the contact results
	$scope.filter_text = '';

	// The method called when the filter "clear" button is clicked
	$scope.clearFilter = function()
	{
		$scope.filter_text = '';
	};

	// An object to store the new contact data
	$scope.newcontact = {};

	// Called to add a new contact
	$scope.createContact = function()
	{
		// To Do: Add validation

		// Assuming the validation passes (To Do), add the contact
		var newContact = $scope.newcontact;
		newContact.id = ++$scope.contact_id_generator;
		$scope.contacts.push( newContact );

		// Send the user to the contact list page
		$location.path( '' );
	};
} );

// Create the routes for this app
myApp.config( function( $routeProvider )
{
	$routeProvider.when( '/new', {
		templateUrl: 'templates/contact_new.html',
		controller: 'contactListCtrl'
	} );

	// The default route, shows the sortable, filterable contact list
	$routeProvider.otherwise( {
		templateUrl: 'templates/contacts_main.html',
		controller: 'contactListCtrl'
	} );
} );
