"use strict"

// Declare our module
var myApp = angular.module( 'contactListApp', ['ngRoute'] );

// Add our controller to our module
myApp.controller( 'contactListCtrl', function( $scope, $http, $location )
{
	// A function called to load the relevant data onto the scope.  It only executes once
	var initializeData = function()
	{
		if( $scope.initialized === undefined )
		{
			// Make sure this function only executes once
			$scope.initialized = true;

			// A variable used to generate ids (primary key) for each contact that 
			// is generated by this app (in place of a backend)
			$scope.contact_id_generator = false;

			// The templates available to our app
			$scope.templates = [ 
				{ name: 'list', url: 'templates/contacts_list.html' }
				,{ name: 'table', url: 'templates/contacts_table.html' } ];

			// The currently selected template
			$scope.template = $scope.templates[0];

			// Load the contact list from the server
			$http.get( 'data/contacts.php' ).success( function( data )
			{
				$scope.contacts = data;

				// Set the id generator to the id of the last contact loaded from the server
				// plus one (so we don't need a backend and so the code will be easily used with a backend)
				$scope.contact_id_generator = $scope.contacts.length;
			} );

			// Load the list of states from the server
			$http.get( 'data/states.php' ).success( function( data )
			{
				$scope.states = data;
			} );

			// The text used to filter the contact results
			$scope.filter_text = '';
		}
	}();

	// The method called when the filter "clear" button is clicked
	$scope.clearFilter = function()
	{
		$scope.filter_text = '';
	};

	// An object to store the new contact data
	$scope.newcontact = {};

	// Called to add a new contact
	$scope.createContact = function()
	{
		// To Do: Add validation

		// Assuming the validation passes (To Do), add the contact
		var newContact = $scope.newcontact;
		newContact.id = ++$scope.contact_id_generator;
		$scope.contacts.push( newContact );

		// Send the user to the contact list page
		$location.path( '' );
	};

	// Called to cancel the adding of a new contact
	$scope.cancelCreateContact = function()
	{
		$location.path( '' );
	}
} );

// Create the routes for this app
myApp.config( function( $routeProvider )
{
	$routeProvider.when( '/new', {
		templateUrl: 'templates/contact_new.html',
		controller: 'contactListCtrl'
	} );

	// The default route, shows the sortable, filterable contact list
	$routeProvider.otherwise( {
		templateUrl: 'templates/contacts_main.html',
		controller: 'contactListCtrl'
	} );
} );
